import { BaseEdge, type EdgeProps } from "reactflow";

const BEND_RADIUS = 4;

/**
 * Right-angle elbow edge with rounded corners.
 *
 * The vertical leg sits at the midpoint between source and target, plus
 * `data.offset` (signed). Per-edge offsets are generated by the canvas as
 * `(i - (N-1)/2) * step` so a parent's N edges form a bundle of stripes
 * centered between the parent and child columns — the middle stripe
 * exactly halfway, others equidistant on either side.
 */
export function ElbowEdge({
  sourceX,
  sourceY,
  targetX,
  targetY,
  style,
  markerEnd,
  data,
}: EdgeProps) {
  const offset = (data?.offset as number | undefined) ?? 0;
  const center = (sourceX + targetX) / 2;
  // Clamp so the bend never overshoots either side — that's what causes
  // U-turns / back-bends when offsets are large.
  const minMid = sourceX + BEND_RADIUS + 4;
  const maxMid = targetX - BEND_RADIUS - 4;
  const midX = Math.max(minMid, Math.min(center + offset, maxMid));

  const dy = targetY - sourceY;
  if (Math.abs(dy) < 1) {
    // Straight horizontal line.
    const path = `M ${sourceX} ${sourceY} L ${targetX} ${targetY}`;
    return <BaseEdge path={path} style={style} markerEnd={markerEnd} />;
  }

  // Limit corner radius so it doesn't exceed any leg's length.
  const r = Math.min(
    BEND_RADIUS,
    Math.abs(dy) / 2,
    Math.abs(midX - sourceX),
    Math.abs(targetX - midX),
  );
  const v = dy > 0 ? 1 : -1; // 1 = down, -1 = up

  // M source → horizontal → quarter-circle corner (Q) → vertical → quarter-circle
  // corner → horizontal → target. Quadratic curves with control point at the
  // exact corner produce a clean rounded bend.
  const path = [
    `M ${sourceX} ${sourceY}`,
    `L ${midX - r} ${sourceY}`,
    `Q ${midX} ${sourceY} ${midX} ${sourceY + v * r}`,
    `L ${midX} ${targetY - v * r}`,
    `Q ${midX} ${targetY} ${midX + r} ${targetY}`,
    `L ${targetX} ${targetY}`,
  ].join(" ");

  return <BaseEdge path={path} style={style} markerEnd={markerEnd} />;
}
